Repository Cambricon/mlu-ops, pull requests merged in 2022-05, with the labels that each got.

#17 feat(bangc-ops): add pre-commit code style check, bangc develop support.
  CPPLINT.cfg
  bangc-ops/core/cnlog.cpp
  bangc-ops/core/cnlog.h
  bangc-ops/core/context.cpp
  bangc-ops/core/logging.cpp
  bangc-ops/core/logging.h
  bangc-ops/core/macros.h
  bangc-ops/core/platform/posix/env_time.cpp
  bangc-ops/core/tensor.cpp
  bangc-ops/core/tensor.h
  bangc-ops/core/tool.cpp
  bangc-ops/core/tool.h
  bangc-ops/core/type.cpp
  bangc-ops/core/util.cpp
  bangc-ops/kernels/abs/abs.mlu
  bangc-ops/kernels/abs/abs_device.mlu
  bangc-ops/kernels/binary_op/binary_op_3pipeline.h
  bangc-ops/kernels/binary_op/binary_op_host.h
  bangc-ops/kernels/binary_op/binary_op_host.mlu
  bangc-ops/kernels/div/div.h
  bangc-ops/kernels/div/div.mlu
  bangc-ops/kernels/div/div_device.mlu
  bangc-ops/kernels/kernel.h
  bangc-ops/kernels/log/log.h
  bangc-ops/kernels/log/log.mlu
  bangc-ops/kernels/log/log_device.mlu
  bangc-ops/kernels/sqrt/sqrt.h
  bangc-ops/kernels/sqrt/sqrt.mlu
  bangc-ops/kernels/sqrt/sqrt_device.mlu
  bangc-ops/kernels/sqrt_backward/sqrt_backward.h
  bangc-ops/kernels/sqrt_backward/sqrt_backward.mlu
  bangc-ops/kernels/sqrt_backward/sqrt_backward_device.mlu
  bangc-ops/kernels/unary_op/unary_op_3pipeline.h
  bangc-ops/kernels/unary_op/unary_op_5pipeline.h
  bangc-ops/kernels/unary_op/unary_op_host.h
  bangc-ops/kernels/unary_op/unary_op_host.mlu
  bangc-ops/mlu_op.h
  bangc-ops/test/mlu_op_gtest/src/zoo/abs/abs.cpp
  bangc-ops/test/mlu_op_gtest/src/zoo/div/div.cpp
  bangc-ops/test/mlu_op_gtest/src/zoo/div/div.h
  bangc-ops/test/mlu_op_gtest/src/zoo/log/log.cpp
  bangc-ops/test/mlu_op_gtest/src/zoo/sqrt/sqrt.cpp
  bangc-ops/test/mlu_op_gtest/src/zoo/sqrt_backward/sqrt_backward.cpp
  env.sh
  requirements.txt
  tools/format2google
  tools/pre-commit
Labels: BANGC

#31 fix(bangc-ops): set nightly test at 15:00 according to time of CI's execution on GitHub
  .github/workflows/ci.yaml
Labels: BANGC

#34 fix(bangc-ops): delete unused test mluop api in mlu_op.h
  bangc-ops/mlu_op.h
Labels: BANGC

#32 [DOCS] Add pr.md and contribute.md
  CONTRIBUTION.md
  docs/pr.md
  docs/pr_createpr.png
  docs/pr_fork.png
Labels: documentation

#38 [Feature](bangpy-ops): add pylint check into pre-commit check.
  tools/pre-commit
Labels: BANGPy
