Repository Cambricon/mlu-ops, pull requests merged in 2024-05, with the labels that each got.

#993 [Fix](mlu-ops): Fix an error of perf analyser
  tools/perf_analyse/parser.py
Labels: Bug Fix

#1032 [Docs](mlu-ops): Update release note for v1.2.0
  .github/workflows/daily.yaml
  .github/workflows/mluops_all_system_ci.yaml
  .github/workflows/mluops_ci.yaml
  docs/api_guide/update.rst
  docs/release_notes/mlu_ops.rst
  docs/user_guide/2_update_history/index.rst
  installer/centos7.5/SPECS/mluops-independent.spec
  installer/independent/debian/changelog
  mlu_op.h
Labels: Documentation

#1036 [Feature](mlu-ops): Replace atomic_add with atomic_reduce_add
  kernels/carafe/carafe_block.mlu
  kernels/deform_roi_pool/deform_roi_pool_union1.mlu
  kernels/psroipool/psroipool_block.mlu
  kernels/roi_align_rotated/roi_align_rotated_block.mlu
  kernels/roi_crop/roi_crop_block.mlu
  kernels/rotated_feature_align/rotated_feature_align_block.mlu
Labels: Feature
