Repository Cambricon/mlu-ops, pull requests merged in 2024-12, with the labels that each got.

#1162 [Fix](mluOpRotatedFeatureAlignForward): Fix memset warning
  kernels/rotated_feature_align/rotated_feature_align_block.mlu
Labels: Bug Fix

#1163 [Fix](mluOpRotatedFeatureAlignForward): Fix memset warning
  kernels/rotated_feature_align/rotated_feature_align_block.mlu
Labels: Bug Fix

#1170 [Feature](mlu-ops): adapt scatter,gather
  kernels/box_iou_rotated/box_iou_rotated_utils.h
  kernels/generate_proposals_v2/generate_proposals_v2_union1_500.mlu
  kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
  kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
  kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_utils.h
  kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
  kernels/roi_align_rotated/roi_align_rotated_forward_vector.mlu
  kernels/utils/scatter_gather.h
  kernels/voxel_pooling_forward/voxel_pooling_forward_union1.mlu
  kernels/voxelization/voxelization_kernel.mlu
Labels: Feature

#1171 [Docs](mlu-ops): Update version date.
  docs/api_guide/update.rst
Labels: Documentation

#1172 [Docs](mlu-ops): Update version date.
  docs/api_guide/update.rst
Labels: Documentation

#1174 [Fix](mluOpExecFFT): fix core dump, scale factor and one point comput…
  kernels/fft/c2c_fft/c2c_fft_host.cpp
  kernels/fft/common/fft_basic_ops.cpp
  kernels/fft/common/fft_common_kernels.mlu
  kernels/fft/fft.cpp
  kernels/fft/fft.h
  kernels/fft/fft_optm_device/fft_c2c_stockham_nram.h
  kernels/fft/fft_optm_device/fft_two-level_network_c2c_device.mlu
  kernels/fft/fft_optm_device/fft_two-level_network_c2r_device.mlu
  kernels/fft/fft_optm_device/fft_two-level_network_r2c_device.mlu
  kernels/fft/irfft/irfft_host.cpp
  kernels/fft/rfft/rfft_host.cpp
  kernels/tensor_stride_process/tensor_stride_process_host.cpp
Labels: Bug Fix

#1159 [Fix](mluOpExecFFT): fix core dump, scale factor and one point compute error
  kernels/fft/c2c_fft/c2c_fft_host.cpp
  kernels/fft/common/fft_basic_ops.cpp
  kernels/fft/common/fft_common_kernels.mlu
  kernels/fft/fft.cpp
  kernels/fft/fft.h
  kernels/fft/fft_optm_device/fft_c2c_stockham_nram.h
  kernels/fft/fft_optm_device/fft_two-level_network_c2c_device.mlu
  kernels/fft/fft_optm_device/fft_two-level_network_c2r_device.mlu
  kernels/fft/fft_optm_device/fft_two-level_network_r2c_device.mlu
  kernels/fft/irfft/irfft_host.cpp
  kernels/fft/rfft/rfft_host.cpp
  kernels/tensor_stride_process/tensor_stride_process_host.cpp
Labels: Bug Fix

#1180 [Fix](mluOpExecFFT): fix bug about 2d n0==1 || n1==1.
  kernels/fft/c2c_fft/c2c_fft_host.cpp
  kernels/fft/irfft/irfft_host.cpp
  kernels/fft/rfft/rfft_host.cpp
Labels: Bug Fix

#1181 [Fix](mluOpExecFFT): fix bug about 2d n0==1 || n1==1.
  kernels/fft/c2c_fft/c2c_fft_host.cpp
  kernels/fft/irfft/irfft_host.cpp
  kernels/fft/rfft/rfft_host.cpp
Labels: Bug Fix

#1151 [Feature](mluOpCore): access variable in tensor struct through function in tensor.cpp and tensor.h
  core/gen_case.cpp
  core/gen_case.h
  core/tensor.cpp
  core/tensor.h
  test/mlu_op_gtest/pb_gtest/src/zoo/active_rotated_filter_forward/active_rotated_filter_forward.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/fft/fft.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/masked_col2im_forward/masked_col2im_forward.cpp
Labels: Feature

#1183 [Feature](mlu-ops): Update Cmakelists.txt for --no-neuware-version-check
  CMakeLists.txt
  independent_build.sh
Labels: Feature

#1184 [Feature](mlu-ops): Compile mtp_613 by default
  CMakeLists.txt
Labels: Feature

#1177 [Docs](mlu-ops): Update docs for v1.4.2
  .github/workflows/daily.yaml
  .github/workflows/mluops_ci.yaml
  README.md
  build.property
  docs/api_guide/update.rst
  docs/release_notes/mlu_ops.rst
  docs/user_guide/2_update_history/index.rst
  installer/centos7.5/SPECS/mluops-independent.spec
  installer/independent/debian/changelog
  mlu_op.h
Labels: Documentation

#1182 [Docs](mlu-ops): Update docs for v1.4.2
  .github/workflows/daily.yaml
  .github/workflows/mluops_ci.yaml
  README.md
  build.property
  docs/api_guide/update.rst
  docs/release_notes/mlu_ops.rst
  docs/user_guide/2_update_history/index.rst
  installer/centos7.5/SPECS/mluops-independent.spec
  installer/independent/debian/changelog
  mlu_op.h
Labels: Documentation

#1186 [Fix](mluOpNmsRotated): fix race_check error.
  kernels/nms_rotated/nms_rotated_union1.mlu
Labels: Bug Fix

#1185 [Docs](mlu-ops): update bang-c-ops-develop doc.
  docs/BANG-C-OPS-Develop-Guide.md
  docs/images/figure4-1.png
  docs/images/figure4-2.png
  docs/images/figure4-3.png
  docs/images/figure4-4.png
  docs/images/figure4-5.png
  docs/images/hardwarehierarchy.png
  docs/images/memorymodel.png
  docs/images/pingpong.png
  docs/images/pingpong4.png
  docs/images/pingpong5.png
  docs/images/taskgrid.png
Labels: Documentation

#1179 [Feature](mlu-ops): add lite-interface.
  bangc_helper_dtype.h
  bangc_kernels.h
  independent_build.sh
  kernels/adam_w/adam_w.cpp
  kernels/adam_w/adam_w.h
  kernels/adam_w/adam_w_union1.mlu
  mlu_op.h
  samples/mlu-ops/abs_sample/build.sh
  samples/mlu-ops/build.sh
  samples/mlu-ops/fault_sample/build.sh
  samples/mlu-ops/poly_nms_sample/build.sh
  scripts/gen_symbol_visibility_map.py
  test/mlu_op_gtest/CMakeLists.txt
  test/mlu_op_gtest/pb_gtest/include/executor.h
  test/mlu_op_gtest/pb_gtest/src/zoo/adam_w/adam_w.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/adam_w/adam_w.h
Labels: Feature
