Repository Cambricon/mlu-ops, pull requests merged in 2024-10, with the labels that each got.

#1096 [Feature](mlu-ops): use bang_filter replace to bang_collect/select
  kernels/ball_query/ball_query_union1.mlu
  kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
  kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_utils.h
  kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
  kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_small_channel_union1.mlu
  kernels/roiaware_pool3d/roiaware_pool3d_union1.mlu
  kernels/roipoint_pool3d/roipoint_pool3d_union1.mlu
  kernels/roipoint_pool3d/roipoint_pool3d_union1_large_boxes_num.mlu
  kernels/sparse_conv/get_indice_pairs/get_indice_pairs_block.mlu
Labels: Feature

#1099 [Fix](mluOpSetFFTReserveArea): fix fft bug.
  kernels/fft/c2c_fft/c2c_fft_host.cpp
  kernels/fft/fft.cpp
  kernels/fft/irfft/irfft_host.cpp
  kernels/fft/rfft/rfft_host.cpp
Labels: Bug Fix

#1109 [Fix](mluOpLgamma): fix lgamma for large tensor.
  kernels/lgamma/lgamma.cpp
  kernels/lgamma/lgamma.h
  kernels/lgamma/lgamma_block.mlu
  test/mlu_op_gtest/pb_gtest/src/zoo/lgamma/test_case/case_0.prototxt
Labels: Bug Fix

#1114 [Fix](mluOpLgamma): fix formula in lgamma doc
  docs/design_docs/lgamma/lgamma.md
Labels: Bug Fix

#1089 [Feature](mlu-ops): change getSizeOfDataType to mluOpGetSizeOfDataType.
  test/mlu_op_gtest/pb_gtest/src/executor.cpp
  test/mlu_op_gtest/pb_gtest/src/executor_float_old.cpp
  test/mlu_op_gtest/pb_gtest/src/parser.cpp
  test/mlu_op_gtest/pb_gtest/src/stride.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_forward/indice_convolution_forward.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/moe_dispatch_backward_data/moe_dispatch_backward_data.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/moe_dispatch_forward/moe_dispatch_forward.cpp
Labels: Feature

#1125 [Docs](mlu-ops): Add logspace/lgamma in rst and op_list.
  docs/MLU-OPS-OpList.md
  docs/design_docs/lgamma/lgamma.md
  docs/user_guide/9_operators/index.rst
Labels: Documentation

#1129 [Fix](mlu-ops):modify MLUOP to MLU-OPS in log.
  core/cnlog.cpp
  core/context.cpp
Labels: Bug Fix

#1127 [Fix](mlu-ops):fix racecheck error.
  kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
  kernels/generate_proposals_v2/generate_proposals_v2_union1_500.mlu
  kernels/rotated_feature_align/rotated_feature_align_block.mlu
  kernels/voxelization/voxelization_kernel.mlu
Labels: Bug Fix

#1131 [Fix](mluOpMsDeformAttnForward): fix gen_case.
  kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_forward.mlu
Labels: Bug Fix

#1132 [Fix](mluOpLogspace): Fix logspace bug.
  docs/design_docs/logspace/logspace.md
  kernels/logspace/logspace.cpp
  kernels/logspace/logspace_block.mlu
Labels: Bug Fix

#1134 [Fix](mlu-ops): fix gen-case dump float16 bug.
  core/gen_case.h
Labels: Bug Fix

#1133 [Docs](mlu-ops): add build option '-p/--perf' user guide
  docs/MLU-OPS-Compile-Develop-And-Test.md
Labels: Documentation
