Repository Cambricon/mlu-ops, pull requests merged in 2024-02, with the labels that each got.

#934 [Feature](mluOpExecFFT)): add fft op
  docs/design_docs/fft/fft.md
  docs/user_guide/9_operators/index.rst
  kernels/fft/README.md
  kernels/fft/c2c_fft/c2c_fft.h
  kernels/fft/c2c_fft/c2c_fft_host.cpp
  kernels/fft/common/fft_basic_ops.cpp
  kernels/fft/common/fft_basic_ops.h
  kernels/fft/common/fft_common_kernels.h
  kernels/fft/common/fft_common_kernels.mlu
  kernels/fft/fft.cpp
  kernels/fft/fft.h
  kernels/fft/fft_optm_device/fft_cooley-tukey_ux_device.mlu
  kernels/fft/fft_optm_device/fft_stockham_u1_device.mlu
  kernels/fft/irfft/irfft.h
  kernels/fft/irfft/irfft_host.cpp
  kernels/fft/rfft/rfft.h
  kernels/fft/rfft/rfft_host.cpp
  kernels/tensor_stride_process/tensor_stride_process_host.cpp
  kernels/utils/common.h
  mlu_op.h
  test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_ExecFFT.cpp
  test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_MakeFFTPlanMany.cpp
  test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_SetFFTReserveArea.cpp
  test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_general.cpp
  test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_plan_descriptor.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/fft/fft.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/fft/fft.h
  test/mlu_op_gtest/pb_gtest/src/zoo/fft/test_case/fft_0.prototxt
Labels: New Op

#946 [Docs](mlu-ops): Update docs for v1.0.0
  .github/workflows/daily.yaml
  .github/workflows/mluops_all_system_ci.yaml
  .github/workflows/mluops_ci.yaml
  README.md
  build.property
  docs/api_guide/update.rst
  docs/release_notes/mlu_ops.rst
  docs/user_guide/2_update_history/index.rst
  docs/user_guide/9_operators/index.rst
  installer/centos7.5/SPECS/mluops-independent.spec
  mlu_op.h
Labels: Documentation

#947 [Docs](mlu-ops): Update docs for v1.0.0
  .github/workflows/daily.yaml
  .github/workflows/mluops_all_system_ci.yaml
  .github/workflows/mluops_ci.yaml
  README.md
  build.property
  docs/api_guide/update.rst
  docs/release_notes/mlu_ops.rst
  docs/user_guide/2_update_history/index.rst
  docs/user_guide/9_operators/index.rst
  installer/centos7.5/SPECS/mluops-independent.spec
  kernels/tensor_stride_process/tensor_stride_process_host.cpp
  mlu_op.h
Labels: Documentation

#948 [Fix](mluOpPriorBox):fix gencase bug.
  kernels/prior_box/prior_box.cpp
Labels: Bug Fix

#949 [Fix](mluOpPriorBox):fix gencase bug.
  kernels/prior_box/prior_box.cpp
Labels: Bug Fix

#952 [Fix](mluOpPolyNms):Add real data related op poly_nms into test_list.
  test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Labels: Bug Fix

#954 [Fix](mluOpDiffIouRotatedSortVerticesForward): Add diff_iou_rotated api name to test_list
  test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Labels: Bug Fix

#955 [Fix](mluOpExecFFT):Fix fft bug.
  kernels/utils/common.h
Labels: Bug Fix

#956 [Fix](mlu-ops): fix mlu_only op_list
  docs/design_docs/masked_col2im_forward/masked_col2im_forward.md
  docs/design_docs/psroipool_backward/psroipool_backward.md
  test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Labels: Bug Fix

#958 [Docs](yolo_box): test_list add yolo_box
  docs/design_docs/yolo_box/yolo_box.md
  test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Labels: Bug Fix

#957 [Fix](mlu-ops): fix workspacefree() bug.
  test/mlu_op_gtest/pb_gtest/src/zoo/active_rotated_filter_forward/active_rotated_filter_forward.h
  test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.h
  test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.h
  test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.h
  test/mlu_op_gtest/pb_gtest/src/zoo/masked_col2im_forward/masked_col2im_forward.h
  test/mlu_op_gtest/pb_gtest/src/zoo/moe_dispatch_backward_gate/moe_dispatch_backward_gate.h
  test/mlu_op_gtest/pb_gtest/src/zoo/poly_nms/poly_nms.h
  test/mlu_op_gtest/pb_gtest/src/zoo/roiaware_pool3d_forward/roiaware_pool3d_forward.h
  test/mlu_op_gtest/pb_gtest/src/zoo/roipoint_pool3d/roipoint_pool3d.h
  test/mlu_op_gtest/pb_gtest/src/zoo/three_nn_forward/three_nn_forward.h
  test/mlu_op_gtest/pb_gtest/src/zoo/voxelization/voxelization.h
Labels: Bug Fix

#961 [Fix](mluOpExecFFT): Fix fft doc bug.
  kernels/fft/fft_optm_device/fft_cooley-tukey_ux_device.mlu
Labels: Bug Fix
