Repository Cambricon/mlu-ops, pull requests merged in 2024-03, with the labels that each got.

#966 [Docs](mlu-ops):update operators index.rst.
  docs/user_guide/9_operators/index.rst
Labels: Documentation

#967 [Feature](indice_convolution_forward): add fool-check for tensor size
  kernels/sparse_conv/indice_convolution_forward/indice_convolution_forward.cpp
Labels: Feature

#973 [Fix](mluOpSqrt,mluOpBorderAlignForward): fix gen-case.
  kernels/border_align/border_align_backward/border_align_backward.cpp
  kernels/border_align/border_align_forward/border_align_forward.cpp
  kernels/sqrt/sqrt.cpp
  test/mlu_op_gtest/pb_gtest/src/zoo/border_align_forward/test_case/border_align_forward_0.prototxt
  test/mlu_op_gtest/pb_gtest/src/zoo/sqrt/sqrt.cpp
Labels: Bug Fix

#975 [Fix](mluOpActiveRotatedFilterForward): Fix gencase bug.
  docs/design_docs/active_rotated_filter_forward/active_rotated_filter_forward.md
  kernels/active_rotated_filter/active_rotated_filter.cpp
  test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Labels: Bug Fix

#976 [Feature](mluOpAdamW): fix adamw gen_case
  kernels/adam_w/adam_w.cpp
  mlu_op.h
  test/mlu_op_gtest/pb_gtest/src/zoo/adam_w/test_case/case_0.prototxt
Labels: Feature

#977 [Feature](mlu-ops): Support mluops static library compiling.
  CMakeLists.txt
  independent_build.sh
  samples/mlu-ops/abs_sample/CMakeLists.txt
  samples/mlu-ops/abs_sample/build.sh
  samples/mlu-ops/env.sh
Labels: Feature

#978 [Feature](mlu-ops): Adapt compiling to version change in build.property.
  cmake/generate_package_info.cmake
  docs/api_guide/update.rst
  docs/user_guide/2_update_history/index.rst
Labels: Feature

#980 [Doc](mlu-ops): update release note
  .github/workflows/daily.yaml
  .github/workflows/mluops_all_system_ci.yaml
  .github/workflows/mluops_ci.yaml
  build.property
  docs/api_guide/update.rst
  docs/release_notes/mlu_ops.rst
  docs/user_guide/2_update_history/index.rst
  docs/user_guide/9_operators/index.rst
  installer/centos7.5/SPECS/mluops-independent.spec
  installer/independent/debian/changelog
  mlu_op.h
Labels: Documentation
