Repository Cambricon/mlu-ops, pull requests merged in 2024-11, with the labels that each got.

#1139 [Fix](mluOPTensor) Fix double free memory error in tensor.cpp
  core/tensor.cpp
Labels: Bug Fix

#1156 Fix(mluOpFocalLossSigmoidBackward): fix unknown address space warning
  kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
Labels: Bug Fix

#1154 [Fix](mluOpMakeFFTPlanMany): Fix memory leaks bug.
  kernels/fft/common/fft_basic_ops.cpp
Labels: Bug Fix

#1142 [Feature](mluOpDynamicPointToVoxelBackward): to be better performance
  docs/design_docs/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.md
  docs/design_docs/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.md
  kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.cpp
  kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.h
  kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward_union1.mlu
Labels: Feature

#1160 [Fix](mluOpGenerateProposalsV2): fix memcheck bug.
  kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
  kernels/generate_proposals_v2/generate_proposals_v2_union_default.mlu
Labels: Bug Fix

#1161 [Docs](mlu-ops): Update docs for v1.4.0
  .github/workflows/daily.yaml
  .github/workflows/mluops_ci.yaml
  README.md
  build.property
  docs/api_guide/update.rst
  docs/release_notes/mlu_ops.rst
  docs/user_guide/2_update_history/index.rst
  installer/centos7.5/SPECS/mluops-independent.spec
  installer/independent/debian/changelog
  mlu_op.h
Labels: Documentation
